name: CI/CD Pipeline

env:
  AZURE_WEBAPP_NAME: health-calculator-app-js  # nom de votre Azure Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          cd health-calculator-service
          pip install pytest
          python -m unittest test.py
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:latest
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
      
      # Déploiement uniquement si c'est un push sur main (pas pour les pull requests)
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
      
      # Afficher l'URL complète basée sur la sortie du déploiement
      - name: Display App URL
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "*** IMPORTANT: Utilisez cette URL pour accéder à l'application ***"
          echo "Votre application est accessible à: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          echo "Note: L'URL simplifiée sans les suffixes régionaux peut ne pas fonctionner"