name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          cd health-calculator-service
          pip install pytest
          python -m unittest test.py

      # Étapes pour build et push Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/health-calculator:latest
            ghcr.io/${{ github.repository_owner }}/health-calculator:${{ github.sha }}
      
      # Déployer avec l'image Docker
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy to Azure Web App
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'health-calculator-app-js'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ github.repository_owner }}/health-calculator:${{ github.sha }}'
          
      - name: Display App URL
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Application successfully deployed to https://health-calculator-app-js.azurewebsites.net"